@api = http://localhost:8080/api/v1/users
# EndPoint users_______________________________________________________________________________
###
GET {{api}}/
###
GET {{api}}/id
###
POST {{api}}
###
PUT {{api}}/id
###
DELETE {{api}}/id